import LenisProvider from "@/components/LenisProvider";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
	subsets: ["latin"],
	variable: "--font-poppins",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Smooth GSAP Transitions",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang='en'>
				<body className={`${poppins.variable} antialiased`}>
					<LenisProvider>
						{/* <NavbarTest /> */}
						<Navbar />
						{children}
					</LenisProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
